branches:
  only:
  - master

os: linux
sudo: required

services:
  - docker

language: python
python: '3.6'

before_install:
    - sudo apt-get install -y sshpass

install:
    - pip install Django
    - pip install Pillow
    - pip install mysqlclient
    - pip install pytz

script: true
  #- python3 manage.py test

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker build -t "${IMAGE_NAME}" .

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}"
  on:
    branch: master

