version: '2'

networks:
  shared:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    networks:
      - shared
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=rayman
     - MYSQL_DATABASE=chickendinner
     - MYSQL_USER=ChickenDinner8
     - MYSQL_PASSWORD=ChickenDinner8

  djangoApp:
    image: raymanng/chickendinner8:django
    build:
      context: .
      dockerfile: Dockerfile_django
    networks:
      - shared

  nginx:
    image: raymanng/chickendinner8:nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    networks:
      - shared
    ports:
     - "80:80"