version: '2'
services:
  djangoApp:
    image: raymanng/chickendinner8
    build: .
    networks:
      - web
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    networks:
      - web
    ports:
     - "80:80"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d
      - ./uwsgi.ini:/etc/uwsgi/uwsgi.ini
      - ./static:/home/static

networks:
  web:
    driver: bridge