version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=rayman
     - MYSQL_DATABASE=chickendinner
     - MYSQL_USER=ChickenDinner8
     - MYSQL_PASSWORD=ChickenDinner8

  djangoApp:
    image: raymanng/chickendinner8:django
    build:
      context: .
      dockerfile: Dockerfile_django
    links:
      - mysql

  nginx:
    image: raymanng/chickendinner8:nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    links:
      - djangoApp
    ports:
     - "80:80"