version: '2'

services:
  djangoApp:
    image: raymanng/chickendinner8
    build: .
    networks:
      - web
    ports:
      - "8000:8000"
    volumes:
    - static-v:/app/static
    - nginx-v:/app/nginx_app.conf
    - uwsgi-v:/app/uwsgi.ini

  nginx:
    image: nginx:alpine
    networks:
      - web
    ports:
     - "80:80"
    volumes:
    - static-v:/home/static
    - nginx-v:/etc/nginx/nginx.conf
    - uwsgi-v:/etc/uwsgi/uwsgi.ini

  mysql:
    image: mysql:5.7
    networks:
      - web
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=rayman
     - MYSQL_DATABASE=chickendinner
     - MYSQL_USER=ChickenDinner8
     - MYSQL_PASSWORD=ChickenDinner8

networks:
  web:
    driver: bridge

volumes:
  static-v:
  nginx-v:
  uwsgi-v: