FROM python:3-alpine
ENV PYTHONUNBUFFERED 1
RUN mkdir /home/django_app
ADD ./ChickenDinner8 /home/django_app
COPY ./uwsgi.ini /home/uwsgi.ini
WORKDIR /django_app
RUN apk update \
    && apk add --no-cache --virtual .build-deps mariadb-dev build-base \
    && apk add jpeg-dev mariadb-client-libs uwsgi uwsgi-python3\
    && pip3 install -r requirements.txt \
    && apk del .build-deps
CMD ["uwsgi", "--ini", "/home/uwsgi.ini"]
