# Generated by Django 2.0.3 on 2018-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=200)),
                ('foodPrice', models.DecimalField(decimal_places=1, max_digits=4)),
                ('foodDescription', models.TextField()),
                ('foodImage', models.ImageField(upload_to='')),
                ('foodPriority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('orderTime', models.TimeField()),
                ('tableNum', models.IntegerField()),
                ('foodOfOrder', models.CharField(max_length=1024)),
                ('payment', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
